# This file was generated by GoReleaser. DO NOT EDIT.
cask "fledge" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "b7e2705255438ae9fdd0ad2cf742337f656d8783d5f344ded149a76ba5fe1894"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "89ee399c2cd8277874291dfb860f31dea5dd7d7109067fd3e7eb34f6f71a2007"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b073d9ac130940521581cdac55afbe40d438ce4e6ce3fce029561e6c077b67a4"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be1126110bf56d86c2a38516c6c3b7da214db86493c2d06c165d43c001d7b5f0"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_linux_arm64.tar.gz"
    end
  end

  name "fledge"
  desc "Release ad hoc iOS builds to your own devices"
  homepage "https://github.com/TheOutdoorProgrammer/fledge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fledge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/fledge"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Point it at a server and it reads the rest from fledge.yaml:

      export FLEDGE_URL=https://fledge.example
      export FLEDGE_TOKEN=...
      fledge release

    Building needs Xcode. Publishing an already-exported archive does not.
  EOS
end
