# This file was generated by GoReleaser. DO NOT EDIT.
cask "fledge" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "b704e1b8c50d238e6216465d68a84189feb2d4fc657b4c1375cd8f442a805a93"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "209857a458a5b192d862e8b2fe49b0214e0d2d4fb44e0fa1f1ad5b34a7ad138a"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88a8cb85e6bcf37974cc4dd50aee707a0c64f70e8244a26eb4643197ddf73ee4"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "747eeb44c03ac1befd0b66c3d30c08836c8bc6d771801000379dc08a9cd88414"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_linux_arm64.tar.gz"
    end
  end

  name "fledge"
  desc "Release ad hoc iOS builds to your own devices"
  homepage "https://github.com/TheOutdoorProgrammer/fledge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fledge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/fledge"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Point it at a server and it reads the rest from fledge.yaml:

      export FLEDGE_URL=https://fledge.example
      export FLEDGE_TOKEN=...
      fledge release

    Building needs Xcode. Publishing an already-exported archive does not.
  EOS
end
