# This file was generated by GoReleaser. DO NOT EDIT.
cask "fledge" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "cc545921a3558f5183627c87ce01fb079e867de92e0310ec8189a1c42991d560"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8800998670444235159cb5854f290924fc10c68be24c5e469f730f00155b8f9c"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "167b8e3089c9a47fdc963a421bbd52774776d8235dc9da2c2891b0f7ef5a4649"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "576ff58af73dd57d7de0407849c3b5a53f457152b0edd811f1a466a9acf8f9f7"
      url "https://github.com/TheOutdoorProgrammer/fledge/releases/download/v#{version}/fledge_linux_arm64.tar.gz"
    end
  end

  name "fledge"
  desc "Release ad hoc iOS builds to your own devices"
  homepage "https://github.com/TheOutdoorProgrammer/fledge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fledge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/fledge"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Point it at a server and it reads the rest from fledge.yaml:

      export FLEDGE_URL=https://fledge.example
      export FLEDGE_TOKEN=...
      fledge release

    Building needs Xcode. Publishing an already-exported archive does not.
  EOS
end
