# This file was generated by GoReleaser. DO NOT EDIT.
cask "planty" do
  version "0.33.11"

  on_macos do
    on_arm do
      sha256 "d6d2df1566a43fe92725b3d6184a1e48b6917e989daafed8ff9def3c10426213"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5d6b7be0227717990cd21808aff114cbb632ab904830def6f6343923ca280543"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a2bc7a796969619ee5ff70e89b49a7b1c7f9cfc60904c24ba8e2b200ab93325c"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "84b2ca372d788096b9d25907396ec9637a609f9c774887287ac1ca97c6c7de40"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_amd64.tar.gz"
    end
  end

  name "planty"
  desc "Keeps houseplants alive. Reports and reminds, and waters nothing on a timer"
  homepage "https://github.com/TheOutdoorProgrammer/planty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/planty"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Every command but `version` talks to Planty's database directly, so it
    needs PLANTY_DATABASE_URL pointing somewhere it can reach. In the cluster
    that is a ClusterIP, so from a laptop it means a port-forward:

      kubectl -n planty port-forward svc/planty-postgres-rw 5432:5432
      export PLANTY_DATABASE_URL='postgres://planty:PASSWORD@localhost:5432/planty?sslmode=disable'

    `planty water` is the only command that moves water. It is never
    scheduled, and running it is a decision you make yourself.
  EOS
end
