# This file was generated by GoReleaser. DO NOT EDIT.
cask "planty" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "cd38a2fd50bea61976015cdc6c4ac53ca4b30e219891e26b3bb451d3af848daa"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3344e4074650865affca8c64dbdcc15044bdb6cf4210befe91bcfcb4012fe3d5"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0079cf90296b3a58e5143ff9cfb8af5e9ecaccf74a5ef0fd0b56fc594520b282"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b6b384703e8a7729f0ca792c05b367590a1d97070cde6461787c92e720d067b"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_arm64.tar.gz"
    end
  end

  name "planty"
  desc "Keeps houseplants alive. Reports and reminds, and waters nothing on a timer"
  homepage "https://github.com/TheOutdoorProgrammer/planty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/planty"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Every command but `version` talks to Planty's database directly, so it
    needs PLANTY_DATABASE_URL pointing somewhere it can reach. In the cluster
    that is a ClusterIP, so from a laptop it means a port-forward:

      kubectl -n planty port-forward svc/planty-postgres-rw 5432:5432
      export PLANTY_DATABASE_URL='postgres://planty:PASSWORD@localhost:5432/planty?sslmode=disable'

    `planty water` is the only command that moves water. It is never
    scheduled, and running it is a decision you make yourself.
  EOS
end
