# This file was generated by GoReleaser. DO NOT EDIT.
cask "planty" do
  version "0.33.0"

  on_macos do
    on_arm do
      sha256 "23868de2c45999a22062dc3551c886784c33c98143cf810acfe22832580c4f43"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "264b9b84052c40a606d3b4c36baddb9caaf7f9842f4e3b06a7cc4c497f8458e7"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "97045e0c5a227db7d737ac046535ac45b7affd93dc5b6236bc2f0c1a8c3aabf9"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "aba003a3e5aebe86ac3e14c547e845f0affa8f5a9ac67a9a4c1c9f821c7badd5"
      url "https://github.com/TheOutdoorProgrammer/planty/releases/download/v#{version}/planty_linux_amd64.tar.gz"
    end
  end

  name "planty"
  desc "Keeps houseplants alive. Reports and reminds, and waters nothing on a timer"
  homepage "https://github.com/TheOutdoorProgrammer/planty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/planty"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Every command but `version` talks to Planty's database directly, so it
    needs PLANTY_DATABASE_URL pointing somewhere it can reach. In the cluster
    that is a ClusterIP, so from a laptop it means a port-forward:

      kubectl -n planty port-forward svc/planty-postgres-rw 5432:5432
      export PLANTY_DATABASE_URL='postgres://planty:PASSWORD@localhost:5432/planty?sslmode=disable'

    `planty water` is the only command that moves water. It is never
    scheduled, and running it is a decision you make yourself.
  EOS
end
