# This file was generated by GoReleaser. DO NOT EDIT.
cask "trailwire" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f4231d7e5eb3500e82df566b69675fc92ca372daa294f43238c4aca96b0a3bfa"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9100d9563e9f58ea5b8e6181d7f2bdb7900b940730441ea36eb47b2d4fafdcc4"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "13d594a15bf3a0fe5e16d0525bd81f195a16b845b5d5e59a1b19b75c683488fd"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4acaff4d0995d4f77e2bee69c2b16d9e321dcf26b9264f4117e4b7ccfa8a99af"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_linux_amd64.tar.gz"
    end
  end

  name "trailwire"
  desc "Local coordination for AI coding agents across different harnesses"
  homepage "https://github.com/TheOutdoorProgrammer/trailwire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trailwire"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/trailwire"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Configure Claude Code, Codex, and Cursor, then restart open sessions:

      trailwire init
  EOS
end
