# This file was generated by GoReleaser. DO NOT EDIT.
cask "trailwire" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "28daa6065d40f8c9cbb039d7f4d9bac2c23c60d1401bb94719863e8a443264e9"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5370e6b840cc244bc336c5f9e29e07487153ce35e867c33e3760bdafe92c1af8"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5f5fc1f71f8c576a2cad36c914fe606dfc890b99e103149844e65c20084247f3"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7fde67d0b45224d7af5b3eabedb82accbe24defbf4d24b7c600169d36af7ed92"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_linux_amd64.tar.gz"
    end
  end

  name "trailwire"
  desc "Local coordination for AI coding agents across different harnesses"
  homepage "https://github.com/TheOutdoorProgrammer/trailwire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trailwire"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/trailwire"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Configure Claude Code, Codex, and Cursor, then restart open sessions:

      trailwire init
  EOS
end
