# This file was generated by GoReleaser. DO NOT EDIT.
cask "trailwire" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "4f19df225adee61b26bccfdc003b27af965894595f48c4a7d1880aa5399b25a3"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "acf88ad3a1ecba9999f0581cda7f03003ed915926dc13837ecb3995effecc3f9"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "581b1152a59c6759c15f0491a0e8d908a33e8d369b38d8db1c7770c00fc46541"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ed7cccf63f7ebe02edcef7f73ed3f5d1828515a68f266f6e2036c81e5f240b8d"
      url "https://github.com/TheOutdoorProgrammer/trailwire/releases/download/v#{version}/trailwire_linux_amd64.tar.gz"
    end
  end

  name "trailwire"
  desc "Local coordination for AI coding agents across different harnesses"
  homepage "https://github.com/TheOutdoorProgrammer/trailwire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trailwire"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/trailwire"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Configure Claude Code, Codex, and Cursor, then restart open sessions:

      trailwire init
  EOS
end
